"""A file to have all the resource locations stored centrally."""


SOUND_SNAP = "res/snap.wav"
SOUND_SUCCESS = "res/success.wav"
SOUND_CLICK = "res/click.wav"

MUSIC_BACKGROUND = "res/purrple-cat-equinox.mp3"

IMG_ONE = "res/one.png"
IMG_TWO_CORNER = "res/two_corner.png"
IMG_TWO_STRAIGHT = "res/two_straight.png"
IMG_THREE = "res/three.png"
IMG_FOUR = "res/four.png"
IMG_TWO_CORNER_S = "res/two_corner_s.png"
IMG_TWO_STRAIGHT_S = "res/two_straight_s.png"
IMG_THREE_S = "res/three_s.png"
IMG_FOUR_S = "res/four_s.png"
IMG_ARROW_RIGHT = "res/arrow_right.png"
IMG_ARROW_RIGHT_HOVER = "res/arrow_right_hover.png"
IMG_MUSIC_ON = "res/music_on.png"
IMG_MUSIC_ON_HOVER = "res/music_on_hover.png"
IMG_MUSIC_OFF = "res/music_off.png"
IMG_MUSIC_OFF_HOVER = "res/music_off_hover.png"
IMG_SOUND_ON = "res/speaker_on.png"
IMG_SOUND_ON_HOVER = "res/speaker_on_hover.png"
IMG_SOUND_OFF = "res/speaker_off.png"
IMG_SOUND_OFF_HOVER = "res/speaker_off_hover.png"

ICON_LOOP = "res/icon_loop.png"
